// SPDX-License-Identifier: Apache-2.0
// The authored v1.yaml is JSON-compatible YAML, so generation needs no
// network-installed toolchain. This script checks the contract and emits the
// deterministic path-name fragment consumed by @scoplen/api.
import { readFile, writeFile } from "node:fs/promises";

const root = new URL(".", import.meta.url);
const document = JSON.parse(await readFile(new URL("v1.yaml", root), "utf8"));
if (document.openapi !== "3.1.0") throw new Error("expected OpenAPI 3.1.0");
const paths = Object.keys(document.paths ?? {}).sort();
if (paths.length < 30) throw new Error(`control-plane contract has only ${paths.length} paths`);
for (const path of paths) {
  if (!path.startsWith("/")) throw new Error(`invalid path: ${path}`);
  const operations = document.paths[path];
  if (!Object.keys(operations).some((method) => ["get", "post", "patch", "delete"].includes(method))) {
    throw new Error(`path has no HTTP operation: ${path}`);
  }
}
const generated = `// SPDX-License-Identifier: Apache-2.0\n// Generated by openapi/generate.mjs.\nexport const controlPlanePaths = ${JSON.stringify(paths, null, 2)} as const;\n`;
await writeFile(new URL("generated-paths.ts", root), generated);
console.log(`validated OpenAPI 3.1 contract with ${paths.length} paths`);
